

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// import NextNProgress from "nextjs-progressbar";
import NextTopLoader from 'nextjs-toploader';
import ClientLayout from "@/components/ClientLayout";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientLayout>
       
        
        {children}
        
      
        </ClientLayout>
      </body>
    </html>
    
  );
}
